image: mcr.microsoft.com/playwright/python:v1.46.0-jammy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - test

smoke:
  stage: test
  # NOTE: Dùng shared runner thì KHÔNG cần tags.
  cache:
    paths:
      - .cache/pip

  before_script:
    - python --version
    - pip install -U pip
    - pip install -r requirements.txt

    # Tạo .env từ CI variables
    - |
      printf "BASE_URL=%s\nLOGIN_PATH=%s\nLOGIN_EMAIL=%s\nLOGIN_PASSWORD=%s\n" \
        "$BASE_URL" "$LOGIN_PATH" "$LOGIN_EMAIL" "$LOGIN_PASSWORD" > .env

    # Giải mã AUTH_STATE_B64 -> auth_state.json (nếu có)
    - |
      if [ -n "$AUTH_STATE_B64" ]; then
        printf "%s" "$AUTH_STATE_B64" | base64 -d > auth_state.json
        echo "auth_state.json restored (bytes=$(wc -c < auth_state.json))"
      else
        echo "AUTH_STATE_B64 not set - will login with email/password"
      fi

  script:
    - pytest

  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - report/
    # Không lưu auth_state.json để tránh lộ token
