stages: [test]

# (khuyến nghị) job chẩn đoán nhanh
diag:
  stage: test
  tags: [win-shell]
  script:
    - '$ErrorActionPreference="Stop"'
    - 'Write-Host "USER: $env:USERNAME@$env:USERDOMAIN"'
    - 'Write-Host "PATH: $env:PATH"'
    - 'where.exe python'
    - 'python -V; pip -V'

smoke:
  stage: test
  tags: [win-shell]
  before_script:
    - '$ErrorActionPreference="Stop"'
    # tạo sẵn thư mục report để tránh cảnh báo
    - 'if (!(Test-Path report)) { New-Item -ItemType Directory -Path report | Out-Null }'
    # khôi phục state nếu dùng AUTH_STATE_B64
    - 'if ($env:AUTH_STATE_B64) { [IO.File]::WriteAllBytes("auth_state.json",[Convert]::FromBase64String($env:AUTH_STATE_B64)) }'
    # cài deps + browsers
    - 'python -m pip install -U pip'
    - 'python -m pip install -r requirements.txt'
    - 'python -m playwright install chromium'
  script:
    # ép pytest tạo html report, kể cả khi fail
    - 'pytest --maxfail=1 --html=report\smoke.html --self-contained-html -q'
  # nếu vì lý do nào đó vẫn chưa có report, tạo file giả để upload
  after_script:
    - 'if (!(Test-Path report\smoke.html)) { "No report generated" | Out-File report\_no_report.txt -Encoding utf8 }'
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - report/**/*
